services:
  forum.api:
    container_name: "Forum.Presentation"
    hostname: "forum.api"
    image: ${DOCKER_REGISTRY-}forumapi
    build:
      context: .
      dockerfile: src/ForumService/Forum.Presentation/Dockerfile
    ports:
        - "7000:8080"
        - "7001:8081"
    depends_on:
        - forum.db
  
  forum.db:
    container_name: "Forum.Database"
    image: mcr.microsoft.com/mssql/server:2022-latest
    user: root
    volumes:
      - ./.containers/forum:/var/opt/mssql/data
    environment:
        ACCEPT_EULA: "Y"
        MSSQL_SA_PASSWORD: StrongPassword123
    ports:
        - "7003:1433"

  identity.api:
    container_name: "Identity.Presentation"
    hostname: "identity.api"
    image: ${DOCKER_REGISTRY-}identityapi
    build:
      context: .
      dockerfile: src/IdentityService/Identity.Presentation/Dockerfile
    ports:
        - "6000:8080"
        - "6001:8081"
    depends_on:
        - identity.db
        - kibana
        - rabbitmq

  identity.db:
    container_name: "Identity.Database"
    image: mcr.microsoft.com/mssql/server:2022-latest
    user: root
    volumes:
      - ./.containers/identity:/var/opt/mssql/data
    environment:
        ACCEPT_EULA: "Y"
        MSSQL_SA_PASSWORD: StrongPassword123
    ports:
        - "6003:1433"

  elasticsearch:
    container_name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:8.7.1
    environment:
        - xpack.security.enabled=false
        - xpack.security.http.ssl.enabled=false
        - discovery.type=single-node
        - ES_JAVA_OPTS=-Xms512m -Xmx512m
    volumes:
      - ./.containers/elasticsearch:/usr/share/elasticsearch/data
    ports:
        - 9200:9200

  kibana:
    container_name: kibana
    image: docker.elastic.co/kibana/kibana:8.7.1
    ports:
        - 5601:5601
    depends_on:
        - elasticsearch
    environment:
        - ELASTICSEARCH_URL=http://localhost:9200

  article.api:
    container_name: "Article.Presentation"
    hostname: "article.api"
    image: ${DOCKER_REGISTRY-}articleapi
    build:
      context: .
      dockerfile: src/ArticleService/Article.Presentation/Dockerfile
    ports:
        - "5000:8080"
        - "5001:8081"
    depends_on:
        - mongodb
        - rabbitmq

  mongodb:
    image: mongo:latest
    ports:
        - "27017:27017"

  rabbitmq:
    image: masstransit/rabbitmq:latest
    ports:
      - "5672:5672"
      - "15672:15672"


  ocelotapigateway:
    container_name: "ApiGateway"
    image: ${DOCKER_REGISTRY-}ocelotapigateway
    build:
      context: .
      dockerfile: src/ApiGateway/OcelotApiGateway/Dockerfile
    ports:
        - "9001:8080"
    depends_on:
        - article.api
        - identity.api
        - forum.api
    links:
        - article.api
        - identity.api
        - forum.api

