services:
  forum.api:
    container_name: "Forum.Presentation"
    hostname: "forum.api"
    image: ${DOCKER_REGISTRY-}forumapi
    build:
      context: .
      dockerfile: src/ForumService/Forum.Presentation/Dockerfile
    ports:
        - "7000:8080"
        - "7001:8081"
    depends_on:
        - forum.db
  
  forum.db:
     container_name: "Forum.Database"
     image: postgres:16.4
     user: root
     environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
     ports:
        - "7004:5432"

  forum.cache:
    image: redis
    hostname: "forum.cache"
    container_name: Forum.Cache
    ports:
      - "6379:6379"

  identity.api:
    container_name: "Identity.Presentation"
    hostname: "identity.api"
    image: ${DOCKER_REGISTRY-}identityapi
    build:
      context: .
      dockerfile: src/IdentityService/Identity.Presentation/Dockerfile
    ports:
        - "6001:8080"
        - "6002:8081"
    depends_on:
        - identity.db
        - rabbitmq

  identity.db:
     container_name: "Identity.Database"
     image: postgres:16.4
     environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
     ports:
        - "6004:5432"

  article.api:
    container_name: "Article.Presentation"
    hostname: "article.api"
    image: ${DOCKER_REGISTRY-}articleapi
    build:
      context: .
      dockerfile: src/ArticleService/Article.Presentation/Dockerfile
    ports:
        - "5000:8080"
        - "5001:8081"
    depends_on:
        - mongodb
        - article.db 
        - rabbitmq

  article.db:
    container_name: "Article.Database"
    image: postgres:16.4
    environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
    ports:
        - "5004:5432"

  mongodb:
    image: mongo:latest
    ports:
        - "27017:27017"

  rabbitmq:
    image: masstransit/rabbitmq:latest
    ports:
      - "6011:5672"
      - "15672:15672"


  ocelotapigateway:
    container_name: "ApiGateway"
    image: ${DOCKER_REGISTRY-}ocelotapigateway
    build:
      context: .
      dockerfile: src/ApiGateway/OcelotApiGateway/Dockerfile
    ports:
        - "9001:8080"
    depends_on:
        - article.api
        - identity.api
        - forum.api
    links:
        - article.api
        - identity.api
        - forum.api

