@OcelotApiGateway_HostAddress = http://localhost:5017

GET {{OcelotApiGateway_HostAddress}}/todos/
Accept: application/json

###

GET {{OcelotApiGateway_HostAddress}}/todos/1
Accept: application/json

###
